ledger/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'ledger'

urlpatterns = [
	#url(r'^$', views.index, name='index'),
	url(r'^accounts/$', views.accounts, name='accounts'),
	#url(r'^parameters/$', views.parameters, name='parameters'),
	url(r'^journals/$', views.journals, name='journals'),
	url(r'^sats/$',views.sats_handler, name='sats'),
	url(r'^sats/(?P<article_id>[0-9]+)/$',views.articles_handler, name='articles'),
	#url(r'^gls/$', views.gls, name='gls'),
	url(r'^journal_basic_expense/$',views.basic_expense_handler, name='basic'),
	url(r'^journal_vickers_journal_form/$',views.vickers_handler, name='vickers'),
	url(r'^journal_sos/$',views.sos_handler, name='sos'),
	url(r'^journal_cpf/$',views.cpf_handler, name='cpf'),
	url(r'^journal_journal_form/$',views.journal_journal_form, name='journal_journal_form'),
	url(r'^journal_fundsupermart/$',views.fundsupermart_handler, name = 'fundsupermart'),
	url(r'^journal_trips/$',views.trips_handler, name = 'trips'),
	url(r'^journal_setting/$',views.setting_handler, name = 'setting'),
	url(r'^sql',views.sql_handler,name='sql'),
	url(r'^transaction',views.transaction,name='transaction'),
	url(r'^check',views.balance_check_handler,name='check'),
	url(r'^stocks',views.stock_handler,name='stocks'),
	url(r'^logout',views.logout_handler,name='logout'),
	url(r'^login',views.login_handler,name='login'),
	url(r'^tables/$',views.tables,name='tables'),
	url(r'^tables/(?P<table_name>[\w]+)/$',views.individual_table,name='individual_table'),
	url(r'', include("social.apps.django_app.urls", namespace="social")),
	#url(r'^googlea39c8dec68b5dc01.html/',views.googlea39c8dec68b5dc01,name='googlea39c8dec68b5dc01')
]

personal_finance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from . import views
admin.autodiscover()

urlpatterns = [
    url(r'^', include('ledger.urls')),
	#url(r'^index',views.index,name='index'),
	url(r'^test_ledger/', include('test_ledger.urls')),
	#url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

ledger/forms.py
from django import forms
import datetime

class sql_form(forms.Form):
	input = forms.CharField(widget=forms.Textarea)
	
class transaction_form(forms.Form):
	input = forms.CharField(widget=forms.Textarea)
	
'''	
class basic_journal_form(forms.Form):
	journal_activities = (
	('salary','salary'),
	('rental','rental'),
	('4G','4G'),
	('Citi dividend','Dividend Card')
	)
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	#choice = forms.ChoiceField(choices = journal_activities,label='activities')
	choice = forms.CharField(max_length=50,required = False)
	amount = forms.DecimalField(max_digits=10, decimal_places=2)
	#initial=datetime.date time.now().strftime("%Y-%m-%d"),

class trip_form(forms.Form):
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	amount = forms.DecimalField(max_digits=10, decimal_places=2)
'''
class vickers_journal_form(forms.Form):
	vickers_activities = (
	('transfer','transfer'),
	('buy','buy'),
	('sell','sell'),
	('dividend','dividend'),
	('mtm','mtm')
	)
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	choice =  forms.ChoiceField(choices = vickers_activities,label='activities')
	ticker = forms.CharField(max_length=10,required = False)
	unit = forms.IntegerField(required = False)
	price = forms.DecimalField(max_digits=10, decimal_places=2,required = False)
'''
class fundsupermart_journal_form(forms.Form):
	vickers_activities = (
	('buy','buy'),
	('sell','sell'),
	('commission','commission'),
	)
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	choice =  forms.ChoiceField(choices = vickers_activities,label='activities')
	fund = forms.CharField(max_length=10)
	unit = forms.DecimalField(max_digits=10, decimal_places=2)
	amount = forms.DecimalField(max_digits=10, decimal_places=2)
	
class dbs_sos_journal_form(forms.Form):
	dbs_sos_activities = (
	('buy','buy'),
	('sell','sell'),
	('dividend','dividend'),
	)
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	choice =  forms.ChoiceField(choices = dbs_sos_activities,label='activities')
	unit = forms.DecimalField(max_digits=10, decimal_places=2,required = False)
	amount = forms.DecimalField(initial=615, max_digits=10, decimal_places=2,required = False)

class cpf_journal_form(forms.Form):
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	ordinary = forms.DecimalField(initial=953.69, max_digits=10, decimal_places=2,required = False)
	special = forms.DecimalField(initial=248.66, max_digits=10, decimal_places=2,required = False)
	medisave = forms.DecimalField(initial=331.65, max_digits=10, decimal_places=2,required = False)
	medishield = forms.DecimalField(max_digits=10, decimal_places=2,required = False)
	dps = forms.DecimalField(max_digits=10, decimal_places=2,required = False)
'''
class journal_form(forms.Form):
	balancesheet_type_choice = (
	('asset','asset'),
	('liability','liability'),
	('income','income'),
	('expense','expense'),
	)
	date = forms.DateField(initial=datetime.datetime.now().strftime("%Y-%m-%d"))
	amount = forms.DecimalField(max_digits=10, decimal_places=2)
	currency = forms.CharField(max_length=10,widget=forms.TextInput(attrs={'placeholder': 'currency'}))
	balancesheet_type_1 = forms.ChoiceField(choices=balancesheet_type_choice)
	balancesheet_type_2 = forms.ChoiceField(choices=balancesheet_type_choice,required = False)
	activity = forms.CharField(max_length=50)
	activity_category = forms.CharField(max_length=50,required = False,widget=forms.TextInput(attrs={'placeholder': 'activity category'}))
	reference = forms.CharField(max_length=100,required = False)
	account_id_1 = forms.CharField(max_length=50,required = False)
	gl_account_1 = forms.CharField(max_length=50)
	account_id_2 = forms.CharField(max_length=50,required = False)
	gl_account_2 = forms.CharField(max_length=50,required = False)
	journal_id = forms.CharField(max_length=100,required = False,widget=forms.TextInput(attrs={'placeholder': 'journal ID'}))
	
class login_form(forms.Form):
	user = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder': 'xqq or xgg'}))
	#user = forms.ChoiceField(widget=forms.RadioSelect, choices=(('xqq', 'xqq',), ('xgg', 'xgg',)))
	password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
	

ledger/views/accounts.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from ledger.models import account_info,cashflow,investment_info,investment_transaction,parameter
from django.contrib.auth.models import User
from ledger.utils import user_name, device
from django.db.models import F,Sum,Avg,Max,Min

################################################################
# name: accounts
# type: function
# import by: ledger/urls
# use: main view module for accounts page
################################################################
# version author	description                      		date
# 1.0     awai		initial release											01/01/2017
# 1.1			awai		use basic-nonpost-post structure		15/10/2017
# 1.2     awai    update cashflow logic								23/10/2017
# 1.3			awai		update investment transaction logic	12/11/2017
# 1.4			awai    remove investment                   26/11/
################################################################

@login_required(login_url='/login/')
def accounts(request):
	
	try:
		d = device(request)
	except Exception as err:
		return render(request,'ledger/error_page.html',{'device':'phone','message':err.args[0]})	

	try:
		user = user_name(request)
	except Exception as err:
		return render(request,'ledger/error_page.html',{'device':d,'message':err.args[0]})
	
	if request.method <> 'POST':
		
		error = ''
		
		#get account info
		try:
			ai = account_info.objects.filter(owner=user).exclude(type = 'shares').exclude(type='funds')
		except:
			error = error + '\naccount_info get value having issue.'
		
		#get cashflow
		try:
			c = cashflow.objects.filter(account_info__in=ai)
		except:
			error = error + '\ncashflow get value having issue.'
		
		#use account info and cashflow to prepare data for template
		try:
			l1 = []
			'''
			i = c.order_by('item').values('item').distinct()
			f = c.order_by('company','account','owner','account_info','item','year','month','currency').values('company','account','owner','account_info','item','year','month','currency').annotate(amount = Sum('amount'))			
			d = c.order_by('year','month').values('year','month').distinct()			
			
			l.append([i,d,f])
			
			#c = cashflow.get('all',account_info.get('cao',user))
			'''
			
			for a in ai:
				ll = []
				i = c.filter(account_info=a).order_by('item').values('item').distinct()
				d = c.filter(account_info=a).order_by('year','month').values('year','month').distinct()
				f = c.filter(account_info=a).order_by('item','year','month','currency').values('item','year','month','currency').annotate(amount = Sum('amount'))
				
				ll.append(a)
				ll.append(i)
				ll.append(d)
				ll.append(f)
				
				l1.append(ll)
				
		except:
			error = error + '\ncashflow prepare data having issue.'
		
		'''
		#get investment info
		try:
			ii = investment_info.objects.filter(owner=user).exclude(identifier = '')
		except:
			error = error + '\ninvestment info get value having issue.'
		
		#get investment transaction
		try:
			#it = investment_transaction.get_transaction('all',investment_info.get('cao',user))
			it = investment_transaction.objects.filter(investment_info__in=ii,transaction_type_1='actual')
		except:
			error = error + '\investment transaction get value having issue.'
			
		#use investment info and investment transaction to prepare data for template
		try:
			l2 = []
			
			for a in ii:
				ll = []
				
				i = it.filter(investment_info=a).order_by('transaction_type_2').values('transaction_type_2').distinct()
				d = it.filter(investment_info=a).order_by('date').values('date').distinct()
				f = it.filter(investment_info=a).order_by('transaction_type_2','date')	
				
				ll.append(a)
				ll.append(i)
				ll.append(d)
				ll.append(f)
				
				l2.append(ll)
				
		except:
			error = error + '\ninvestment_transaction prepare data having issue.'

		try:
			
			for a in ii:
				u = float(a.unit)
				p = float(a.price)
				
				sum = sum + u * p
			
		except:
			error = error + '\ninvestment info get total sum having issue.'
		'''
		if error == '':
			return render(request,'ledger/accounts.html',{'acct':ai.order_by('company','identifier'),
																								 'company':ai.values('company').distinct(),
																									 	  'cf':l1 
																						# 'investments':ii,
																						# 'transaction':l2,
																						#				'user':user,
																			#	'total_investment':sum,
																				#					'device':d
															})
		else:
			#return HttpResponse(error)
			return render(request,'ledger/error_page.html',{'device':d,'message':error})
		
	else:
		return render(request,'ledger/error_page.html',{'device':d,'message':'This page has no POST request'})

ledger/views/all_table_columns.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse

from ledger.models import all_table_columns, all_tables, all_tables_form, all_table_columns_form, all_table_functions

def tables(request):
	if request.method == 'POST':
		t = request.POST.get('table','')
		i = request.POST.get('id','')
		c = request.POST.get('column','')
		v = request.POST.get('value','')
		
		if t == 'test':
			import sys
			import os
			#sys.path.append('/home/alonglry/personal_finance')
			os.system("python /home/alonglry/personal_finance/custom_admin/proxy_model.py preparemigration ledger account.py")
			return ('ok')
			#if os.system("touch abc.txt") == 0:
				# success
			#else:
				# failure
		elif t == 'tables' and i <> 'new' and v <> 'delete':
			all_tables.update(i,c,v)
			return HttpResponse('%s %s %s %s' % (i,t,c,v))
		elif t == 'columns' and i <> 'new' and v <> 'delete':
			all_table_columns.update(i,c,v)
			return HttpResponse('%s %s %s %s' % (i,t,c,v))
		elif t == 'functions' and i <> 'new' and v <> 'delete':
			all_table_functions.update(i,v)
			return HttpResponse('id: %s table: %s value: %s' % (i,t,v))
		elif t == 'tables' and i <> 'new' and v == 'delete':
			obj = all_tables.objects.get(id=i)
			all_table_columns.objects.filter(table_name=obj.table_name,project=obj.project,model_file_name=obj.model_file_name).delete()
			obj.delete()
			return HttpResponse('ok')
		elif t == 'columns' and i <> 'new' and v == 'delete':
			obj = all_table_columns.objects.get(id=i)
			obj.delete()
			return HttpResponse(i + ' in all_table_columns deleted')
		elif t == 'tables' and i == 'new':
			p = request.POST.get('project','')
			f = request.POST.get('model_file_name','')
			t = request.POST.get('table_name','')
			v = request.POST.get('verbose_name','')
			vp = request.POST.get('verbose_name_plural','')
			o = request.POST.get('ordering','')
			d = request.POST.get('definition','')
			m = request.POST.get('model_form','')
			u = request.POST.get('unicode','')
			b = request.POST.get('backup','')
			r = request.POST.get('retention_d','')
			
			obj = all_tables.add(p,f,t,v,vp,o,d,m,u,b,r)
			
			#convert objects into json
			from django.forms.models import model_to_dict
			dict_obj = model_to_dict(obj)
			import json
			serialized = json.dumps(dict_obj)
			
			return HttpResponse(serialized)
		elif t == 'columns' and i == 'new':
			pj = request.POST.get('project','')
			mfn = request.POST.get('model_file_name','')
			tn = request.POST.get('table_name','')	
			s = request.POST.get('sn','')
			c = request.POST.get('column_name','')
			v = request.POST.get('verbose_name','')
			vp = request.POST.get('verbose_name_plural','')
			d = request.POST.get('definition','')
			dv = request.POST.get('default_value','')
			co = request.POST.get('choice_options','')
			dt = request.POST.get('data_type','')
			mil = request.POST.get('min_length','')
			mal = request.POST.get('max_length','')
			dp = request.POST.get('decimal_place','')
			p = request.POST.get('path','')
			n = request.POST.get('nullable','')
			b = request.POST.get('blank','')
			uk = request.POST.get('unique_key','')
			mf = request.POST.get('model_form','')
			fkt = request.POST.get('foreign_key_table','')
			fkc = request.POST.get('foreign_key_column','')
			fkod = request.POST.get('foreign_key_on_delete','')
			asfk = request.POST.get('auto_save_foreign_key','')
			
			obj = all_table_columns.add(pj,mfn,tn,s,c,v,vp,d,dv,co,dt,mil,mal,dp,p,n,b,uk,mf,fkt,fkc,fkod,asfk)
			
			#convert objects into json
			from django.forms.models import model_to_dict
			dict_obj = model_to_dict(obj)
			import json
			serialized = json.dumps(dict_obj)
			
			return HttpResponse(serialized)
		elif t == 'functions' and i == 'new':
			pj = request.POST.get('project','')
			mfn = request.POST.get('model_file_name','')
			tn = request.POST.get('table_name','')	
			v = request.POST.get('value','')
			
			obj = all_table_functions.add(pj,mfn,tn,v)
			
			#convert objects into json
			from django.forms.models import model_to_dict
			dict_obj = model_to_dict(obj)
			import json
			serialized = json.dumps(dict_obj)
			
			return HttpResponse(serialized)
		elif t == 'files' and i == 'new':
			pj = request.POST.get('project','')
			mfn = request.POST.get('model_file_name','')
			tn = request.POST.get('table_name','')
			c = "python /home/alonglry/personal_finance/custom_admin/proxy_model.py preparemigration %s %s %s" % (pj,mfn,tn)
			
			import os
			return HttpResponse(os.popen(c).read())
			
			#if os.system("touch abc.txt") == 0:
				# success
			#else:
				# failure
	else:
		c = all_table_columns.objects.all()
		t = all_tables.objects.all()
		tf = all_tables_form()
		cf = all_table_columns_form()
		pm = all_tables.get('pm') #project,model_file_name list
		return render(request,'ledger/all_table_columns.html',{'columns':c,
															   'tables':t,
															   'table_form':tf,
															   'column_form':cf,
															   'list':pm})
		
def individual_table(request,table_name):
	if request.method == 'POST':
		t = request.POST.get('table','')
		i = request.POST.get('id','')
		c = request.POST.get('column','')
		v = request.POST.get('value','')
		
		if t == 'tables':
			all_tables.update(i,c,v)
		elif t == 'columns':
			all_table_columns.update(i,c,v)
			
		return HttpResponse('%s %s %s %s' % (i,t,c,v))
			
	else:
		c = all_table_columns.objects.filter(table_name=table_name)
		t = all_tables.objects.filter(table_name=table_name)
		f = all_table_functions.objects.filter(table_name=table_name)
		
		if t:
			return render(request,'ledger/individual_table.html',{'columns':c,'tables':t,'functions':f})
		else:
			return HttpResponseRedirect(reverse('ledger:tables')) 

ledger/templates/ledger/articles.html
<h1>articles</h1>

{% for a in article %}

<h2>{{ a.ticker.company }} ({{ a.ticker.ticker }}) - {{ a.src }}</h2>

<p>{{ a.product_type }}</p>
<p>{{ a.strategy }}</p>
<p>{{ a.descr }}</p>
<p><a href="{{ a.url }}" target="_blank">article</a></p>
<p>{{ a.validation }}</p>
<p>{{ a.start_date }}</p>
<p>{{ a.end_date }}</p>
<p>{{ a.ror }}</p>
<p>{{ a.status }}</p>

<img src="https://chart.finance.yahoo.com/z?s={{ a.ticker.ticker }}&t=1m&q=&l=&z=l&a=v&p=s" ><br/>
<img src="../../static/{{ a.screenshot }}">


{% endfor %}

ledger/templates/ledger/check.html
{% load format %}
{% load calculate %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href={% static 'ledger/css/check.css' %}>
</head>
<body>
{% include "ledger/links.html" %}

<h1>balance check</h1>

<table>
	<tr>
		<th>ledger type</th>
		<th>ledger</th>
		<th>currency</th>
		<th>journal</th>
		<th>ledger</th>
		<th>account</th>
		<th>cashflow</th>
	</tr>
	
	{% for j in journal %}<tr>
		<td>{{ j.balancesheet_type }}</td>
		<td>{{ j.gl_account }}</td>
		<td>{{ j.currency }}</td>
		<td class='j'>{{ j.amount }}</td>
		
		<td class='l'>{% for l in ledger %}
			{% if l.balancesheet_type = j.balancesheet_type and l.gl_account = j.gl_account and l.currency = j.currency %}
			{{ l.amount }}
			{% endif %}
		{% endfor %}</td>
		
		<td class='a'>{% for a in account %}
			{% if a.company|add:' '|add:a.identifier = j.account or a.broker_company|add:' '|add:a.account = j.account and a.currency = j.currency %}
			{{ a.amount }}
			{% endif %}
		{% endfor %}</td>
		
		<td class='c'>{% for c in cashflow %}
			{% if c.company|add:' '|add:c.account = j.account and c.currency = j.currency %}
			{{ c.amount }}
			{% endif %}
		{% endfor %}</td>
	</tr>{% endfor %}
	
	{% for j in journalpl %}<tr>
		<td>{{ j.balancesheet_type }}</td>
		<td>{{ j.balancesheet_type }} GLs</td>
		<td>{{ j.currency }}</td>
		<td class='j'>{{ j.amount }}</td>
		
		<td class='l'>{% for l in ledgerpl %}
			{% if l.balancesheet_type = j.balancesheet_type and l.gl_account = j.gl_account and l.currency = j.currency %}
			{{ l.amount }}
			{% endif %}
		{% endfor %}</td>
		
		<td class='a'></td>
		<td class='c'></td>
	</tr>{% endfor %}
	
</table>

</body>
</html>

ledger/templates/ledger/error_page.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
{% if device == 'phone'%}
<head>
	
	<meta  http-equiv='X-UA-Compatible'  content='IE=edge,chrome=1'>
	<meta  name='viewport'  content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0'>
	<meta  name='apple-mobile-web-app-capable'  content='yes'>
	<meta  name='apple-mobile-web-app-status-bar-style'  content='black'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href={% static 'ledger/css/font-awesome.min.css' %}>
  <link rel="stylesheet" type="text/css" href={% static 'ledger/css/card.mobile.css' %}>
  
</head>

<body>
{% include "ledger/links_mobile.html" %}
  
<div class='card'>
	<div class='header'><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something is wrong</div>
  <div class = 'message'> {{ message }} </div>	
</div>
    
</body>
  
{% else %}

<head>
	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href={% static 'ledger/css/font-awesome.min.css' %}>
  <link rel="stylesheet" type="text/css" href={% static 'ledger/css/error_page.desk.css' %}>
  
</head>

<body>
{% include "ledger/links.html" %}
  
<div class='card'>
	<div class='header'><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Something is wrong</div>
  <div class = 'message'> {{ message }} </div>	
</div>
  
{% endif %}
  
</html>

ledger/templates/ledger/gls.html
<h1>GL information</h1>
<table>
<tr>
  <th>GL account</th>
  <th>type</th>
  <th>asset type</th>
  <th>holder</th>
  <th>source</th>
  <th>level 1</th>
  <th>level 2</th>
  <th></th>
</tr>

{% for a in gls %}
<tr>
  <td>{{ a.identifier }}</td>
  <td>{{ a.balancesheet_type }}</td>
  <td>{{ a.asset_type }}</td>
  <td>{{ a.asset_holder }}</td>
  <td>{{ a.asset_source }}</td>
  <td>{{ a.level_1_category }}</td>
  <td>{{ a.level_2_category }}</td>
  <td></td>
</tr>
{% endfor %}

</table>

<form action="{% url 'ledger:gls' %}" method="post">
{% csrf_token %}
{{ forms }}
<input type="submit" value="Submit" />
</form>

ledger/templates/ledger/sql.html
<!DOCTYPE html>
<html>
<head>

<!--codemirror-->
<script src="http://codemirror.net/lib/codemirror.js"></script>
<link rel="stylesheet" href="http://codemirror.net/lib/codemirror.css">
<script src="http://codemirror.net/mode/sql/sql.js"></script>
<script src="http://codemirror.net/addon/edit/matchbrackets.js"></script>
<script src="http://codemirror.net/addon/hint/sql-hint.js"></script>
<style type="text/css">.CodeMirror {border-top: 1px solid black; border-bottom: 1px solid black;}</style>

<script>
window.onload = function() {
  var mime = 'text/x-mariadb';
  // get mime type
  if (window.location.href.indexOf('mime=') > -1) {
    mime = window.location.href.substr(window.location.href.indexOf('mime=') + 5);
  }
  window.editor = CodeMirror.fromTextArea(document.getElementById('id_input'), {
    mode: mime,
    indentWithTabs: true,
    smartIndent: true,
    lineNumbers: true,
    matchBrackets : true,
    autofocus: true,
    extraKeys: {"Ctrl-Space": "autocomplete"},
    hintOptions: {tables: {
      users: {name: null, score: null, birthDate: null},
      countries: {name: null, population: null, size: null}
    }}
  });
};
</script>

<style>
table {
    border-collapse: collapse;
	font-family: monospace;
}

table, td, th {
    border: 1px solid black;
}

/*
div {
	display: inline-block;
    margin: 10px;
    font-family: monospace;
    vertical-align: middle;
    word-wrap: break-word;
    padding: 10px;
}*/

#input1 {
	margin-left: 85%;
    margin-top: 2%;
    vertical-align: bottom;
    border: none;
    background: burlywood;
    border: 1px solid;
    color: white;
    border-radius: 5px;
    padding: 5px 15px;
}
#input1:hover {
    /* color: cornflowerblue; */
    cursor: pointer;
    border-radius: 5px;
    background-color: cornflowerblue;
}
#input1:focus {
    outline: 0;
}
/*
textarea {
	border: none;
    background-color: cornsilk;
	padding: 20px;
	border-bottom-right-radius: 25px;
}
textarea:focus {
	outline: 0;
}*/

tr:hover {
    background-color: #E8F0F1 !important;
}
</style>
</head>
<body>
{% include "ledger/links.html" %}

<h1>SQL</h1>

<div style="    width: 45%;
    display: inline-block;
    margin-bottom: 1%;">
	<form action="{% url 'ledger:sql' %}" method="post">
		{% csrf_token %}
		{{ textbox.non_field_errors }}
		{{ textbox.input }}
		<input type="submit" value="Submit" id='input1'/>
	</form>
</div>

<div style="width: 35%;
    display: inline-block;
    vertical-align: top;
    margin-left: 5%;
    font-family: monospace;">
	{% for a in sql %}
		{{ a.sql }} </br>
	{% endfor %}
</br>
{{ error }}
</div>

<table>
	<tr>
		{% for a in desc %}
		<th nowrap>{{ a }}</th>
		{% endfor %}
	</tr>
	{% for a in data %}
	<tr onmouseover="this.style.backgroundColor='#d6e1e2c9';" onmouseout="this.style.backgroundColor='#ffffff';" style="background-color: rgb(255, 255, 255);">
		{% for b in a %}
		<td nowrap>{{ b }}</td>
		{% endfor %}
	</tr>
	{% empty %}<p></p>
	{% endfor %}
</table>

</body>
</html>